packages:
  - '@doubleaxe/eslint-config'
  - '@doubleaxe/eslint-plugin-module-path-fixer'
  - '@doubleaxe/prettier-config'
  - '@doubleaxe/typescript-config'
  - 'test'
allowBuilds:
  esbuild: true
catalog:
  eslint: ^9.39.4
  prettier: ^3.8.2
  typescript: ^6.0.2
